run:
  # timeout for analysis
  deadline: 4m

linters-settings:
  govet:
    # Don't report about shadowed variables
    check-shadowing: false
  gofmt:
    # simplify code: gofmt with `-s` option, true by default
    simplify: true

linters:
  enable-all: true
  disable:
    - gochecknoglobals
    - gosec
    - funlen
    - maligned
    - interfacer

issues:
  exclude-rules:
    - path: cmd/chantools
      linters:
        - lll